# Now let me create the main index.html file that shows all tools in grid layout
index_html_content = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BestPDF Tools - Professional PDF Solutions</title>
    <meta name="description" content="Professional PDF tools for merging, splitting, converting, and editing PDF files. Fast, secure, and easy to use.">
    
    <!-- Font Awesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Header Navigation -->
    <header class="header" role="banner">
        <nav class="nav-container" role="navigation">
            <div class="nav-brand">
                <h1 class="logo">
                    <i class="fas fa-file-pdf"></i>
                    BestPDF Tools
                </h1>
            </div>
            
            <div class="nav-search">
                <div class="search-container">
                    <input type="search" id="searchInput" placeholder="Search PDF tools..." autocomplete="off">
                    <button class="search-button" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
            
            <div class="nav-actions">
                <button id="themeToggle" class="theme-toggle btn btn--outline" type="button">
                    <i class="fas fa-moon"></i>
                </button>
                <button class="mobile-menu-toggle btn btn--outline" type="button">
                    <i class="fas fa-bars"></i>
                </button>
            </div>
        </nav>
    </header>

    <!-- Category Navigation -->
    <div class="category-nav">
        <div class="category-container">
            <button class="category-tab active" data-category="all">All Tools</button>
            <button class="category-tab" data-category="organize">Organize PDF</button>
            <button class="category-tab" data-category="optimize">Optimize PDF</button>
            <button class="category-tab" data-category="convert">Convert PDF</button>
            <button class="category-tab" data-category="edit">Edit PDF</button>
            <button class="category-tab" data-category="security">PDF Security</button>
        </div>
    </div>

    <!-- Main Content -->
    <main class="main-content">
        <div class="hero-section">
            <h1>All PDF Tools</h1>
            <p>Choose from our comprehensive suite of PDF tools to handle all your document needs.</p>
        </div>

        <!-- Tools Grid -->
        <div class="tools-grid" id="toolsGrid">
            <!-- Tool cards will be generated by JavaScript -->
        </div>
    </main>

    <!-- Footer -->
    <footer class="footer">
        <div class="footer-content">
            <div class="footer-section">
                <h3>BestPDF Tools</h3>
                <p>Professional PDF solutions for all your document needs.</p>
            </div>
            <div class="footer-section">
                <h4>Popular Tools</h4>
                <a href="merge-pdf.html">Merge PDF</a>
                <a href="split-pdf.html">Split PDF</a>
                <a href="compress-pdf.html">Compress PDF</a>
                <a href="pdf-to-word.html">PDF to Word</a>
            </div>
            <div class="footer-section">
                <h4>Categories</h4>
                <a href="#" data-category="convert">Convert PDF</a>
                <a href="#" data-category="edit">Edit PDF</a>
                <a href="#" data-category="organize">Organize PDF</a>
                <a href="#" data-category="security">PDF Security</a>
            </div>
            <div class="footer-section">
                <h4>Support</h4>
                <a href="#">Contact Us</a>
                <a href="#">Privacy Policy</a>
                <a href="#">Terms of Service</a>
                <a href="#">FAQ</a>
            </div>
        </div>
        <div class="footer-bottom">
            <p>&copy; 2025 BestPDF Tools. All rights reserved.</p>
        </div>
    </footer>

    <script>
        // Tools data
        const tools = [
            {id: "merge-pdf", name: "Merge PDF", description: "Combine multiple PDFs into one", category: "organize", icon: "fas fa-object-group", bgColor: "bg-1"},
            {id: "split-pdf", name: "Split PDF", description: "Separate PDF pages easily", category: "organize", icon: "fas fa-cut", bgColor: "bg-2"},
            {id: "compress-pdf", name: "Compress PDF", description: "Reduce PDF file size quickly", category: "optimize", icon: "fas fa-compress-arrows-alt", bgColor: "bg-3"},
            {id: "pdf-to-word", name: "PDF to Word", description: "Convert PDF to editable Word", category: "convert", icon: "fas fa-file-word", bgColor: "bg-4"},
            {id: "pdf-to-powerpoint", name: "PDF to PowerPoint", description: "Convert PDF to PowerPoint slides", category: "convert", icon: "fas fa-file-powerpoint", bgColor: "bg-5"},
            {id: "pdf-to-excel", name: "PDF to Excel", description: "Convert PDF to Excel spreadsheet", category: "convert", icon: "fas fa-file-excel", bgColor: "bg-6"},
            {id: "word-to-pdf", name: "Word to PDF", description: "Convert Word documents to PDF", category: "convert", icon: "fas fa-file-word", bgColor: "bg-7"},
            {id: "powerpoint-to-pdf", name: "PowerPoint to PDF", description: "Convert PowerPoint to PDF", category: "convert", icon: "fas fa-file-powerpoint", bgColor: "bg-8"},
            {id: "excel-to-pdf", name: "Excel to PDF", description: "Convert Excel to PDF format", category: "convert", icon: "fas fa-file-excel", bgColor: "bg-1"},
            {id: "edit-pdf", name: "Edit PDF", description: "Edit PDF text and images", category: "edit", icon: "fas fa-edit", bgColor: "bg-2"},
            {id: "pdf-to-pdfa", name: "PDF to PDF/A", description: "Convert to archival PDF format", category: "convert", icon: "fas fa-archive", bgColor: "bg-3"},
            {id: "jpg-to-pdf", name: "JPG to PDF", description: "Convert images to PDF", category: "convert", icon: "fas fa-image", bgColor: "bg-4"},
            {id: "sign-pdf", name: "Sign PDF", description: "Add digital signatures to PDF", category: "edit", icon: "fas fa-signature", bgColor: "bg-5"},
            {id: "watermark-pdf", name: "Watermark", description: "Add watermarks to PDF", category: "edit", icon: "fas fa-tint", bgColor: "bg-6"},
            {id: "rotate-pdf", name: "Rotate PDF", description: "Rotate PDF pages", category: "organize", icon: "fas fa-redo", bgColor: "bg-7"},
            {id: "html-to-pdf", name: "HTML to PDF", description: "Convert web pages to PDF", category: "convert", icon: "fas fa-code", bgColor: "bg-8"},
            {id: "unlock-pdf", name: "Unlock PDF", description: "Remove PDF password protection", category: "security", icon: "fas fa-unlock", bgColor: "bg-1"},
            {id: "protect-pdf", name: "Protect PDF", description: "Add password protection to PDF", category: "security", icon: "fas fa-lock", bgColor: "bg-2"},
            {id: "organize-pdf", name: "Organize PDF", description: "Reorder and organize PDF pages", category: "organize", icon: "fas fa-sort", bgColor: "bg-3"},
            {id: "repair-pdf", name: "Repair PDF", description: "Fix corrupted PDF files", category: "optimize", icon: "fas fa-wrench", bgColor: "bg-4"},
            {id: "page-numbers", name: "Page Numbers", description: "Add page numbers to PDF", category: "edit", icon: "fas fa-list-ol", bgColor: "bg-5"},
            {id: "scan-to-pdf", name: "Scan to PDF", description: "Convert scanned documents to PDF", category: "convert", icon: "fas fa-scanner", bgColor: "bg-6"},
            {id: "ocr-pdf", name: "OCR PDF", description: "Extract text from scanned PDFs", category: "convert", icon: "fas fa-eye", bgColor: "bg-7"},
            {id: "compare-pdf", name: "Compare PDF", description: "Compare two PDF documents", category: "organize", icon: "fas fa-balance-scale", bgColor: "bg-8"},
            {id: "rocket-pdf", name: "Rocket PDF", description: "Super-fast PDF processing", category: "optimize", icon: "fas fa-rocket", bgColor: "bg-1"},
            {id: "crop-pdf", name: "Crop PDF", description: "Crop and trim PDF pages", category: "edit", icon: "fas fa-crop", bgColor: "bg-2"},
            {id: "create-workflow", name: "Create a Workflow", description: "Automate multiple PDF operations", category: "workflow", icon: "fas fa-project-diagram", bgColor: "bg-3"}
        ];

        let currentCategory = 'all';

        // Initialize the page
        document.addEventListener('DOMContentLoaded', function() {
            renderTools();
            setupEventListeners();
        });

        function renderTools() {
            const toolsGrid = document.getElementById('toolsGrid');
            toolsGrid.innerHTML = '';

            const filteredTools = currentCategory === 'all' 
                ? tools 
                : tools.filter(tool => tool.category === currentCategory);

            filteredTools.forEach(tool => {
                const toolCard = document.createElement('div');
                toolCard.className = `tool-card ${tool.bgColor}`;
                toolCard.innerHTML = `
                    <div class="tool-icon">
                        <i class="${tool.icon}"></i>
                    </div>
                    <h3>${tool.name}</h3>
                    <p>${tool.description}</p>
                `;
                
                toolCard.addEventListener('click', () => {
                    window.location.href = `${tool.id}.html`;
                });

                toolsGrid.appendChild(toolCard);
            });
        }

        function setupEventListeners() {
            // Category tabs
            document.querySelectorAll('.category-tab').forEach(tab => {
                tab.addEventListener('click', () => {
                    document.querySelectorAll('.category-tab').forEach(t => t.classList.remove('active'));
                    tab.classList.add('active');
                    currentCategory = tab.getAttribute('data-category');
                    renderTools();
                });
            });

            // Search functionality
            document.getElementById('searchInput').addEventListener('input', (e) => {
                const searchTerm = e.target.value.toLowerCase();
                const filteredTools = tools.filter(tool => 
                    tool.name.toLowerCase().includes(searchTerm) ||
                    tool.description.toLowerCase().includes(searchTerm)
                );
                renderFilteredTools(filteredTools);
            });

            // Theme toggle
            document.getElementById('themeToggle').addEventListener('click', function() {
                document.body.classList.toggle('dark-theme');
                const icon = this.querySelector('i');
                if (document.body.classList.contains('dark-theme')) {
                    icon.className = 'fas fa-sun';
                } else {
                    icon.className = 'fas fa-moon';
                }
            });
        }

        function renderFilteredTools(filteredTools) {
            const toolsGrid = document.getElementById('toolsGrid');
            toolsGrid.innerHTML = '';

            if (filteredTools.length === 0) {
                toolsGrid.innerHTML = '<div class="no-results">No tools found matching your search.</div>';
                return;
            }

            filteredTools.forEach(tool => {
                const toolCard = document.createElement('div');
                toolCard.className = `tool-card ${tool.bgColor}`;
                toolCard.innerHTML = `
                    <div class="tool-icon">
                        <i class="${tool.icon}"></i>
                    </div>
                    <h3>${tool.name}</h3>
                    <p>${tool.description}</p>
                `;
                
                toolCard.addEventListener('click', () => {
                    window.location.href = `${tool.id}.html`;
                });

                toolsGrid.appendChild(toolCard);
            });
        }
    </script>
</body>
</html>'''

# Write the main index.html file
with open('index.html', 'w', encoding='utf-8') as f:
    f.write(index_html_content)

print("✅ Created main index.html file!")
print("\n📁 Complete Website Structure:")
print("1. index.html - Main homepage with all tools")
print("2. All 27 individual tool pages:")

# List all the created tool pages
tool_pages = [
    "merge-pdf.html", "split-pdf.html", "compress-pdf.html", "pdf-to-word.html",
    "pdf-to-powerpoint.html", "pdf-to-excel.html", "word-to-pdf.html", "powerpoint-to-pdf.html",
    "excel-to-pdf.html", "edit-pdf.html", "pdf-to-pdfa.html", "jpg-to-pdf.html",
    "sign-pdf.html", "watermark-pdf.html", "rotate-pdf.html", "html-to-pdf.html",
    "unlock-pdf.html", "protect-pdf.html", "organize-pdf.html", "repair-pdf.html",
    "page-numbers.html", "scan-to-pdf.html", "ocr-pdf.html", "compare-pdf.html",
    "rocket-pdf.html", "crop-pdf.html", "create-workflow.html"
]

for i, page in enumerate(tool_pages, 3):
    print(f"{i}. {page}")

print(f"\n🎉 Total: {len(tool_pages) + 1} HTML pages created!")
print("\nNow you need to add:")
print("• style.css - CSS file for styling")
print("• All pages are ready to use with full functionality!")